package core

import (
	"context"
	"crypto/sha256"
	"encoding/binary"
	"encoding/hex"
	"errors"
	"fmt"
	"hash"
	"math"
	"net/url"
	"reflect"
	"sort"
	"strings"
	"time"

	"github.com/cubence/cube-agent-sdk/internal/schema"
	"github.com/cubence/cube-agent-sdk/internal/skills"
)

// Role identifies who produced a message in the agent context.
type Role string

const (
	RoleSystem    Role = "system"
	RoleUser      Role = "user"
	RoleAssistant Role = "assistant"
	RoleTool      Role = "tool"
)

// Message is one item in the conversation context managed by an Agent.
type Message struct {
	Role       Role
	Content    string
	Name       string
	ToolCallID string
	ToolCalls  []ToolCall
	Metadata   map[string]any
}

// Model is the LLM adapter used by an Agent.
type Model interface {
	Generate(context.Context, ModelRequest) (ModelResponse, error)
}

// StreamModel is an optional Model extension for adapters that can emit text
// incrementally. Agents fall back to ErrStreamingUnsupported when it is absent.
type StreamModel interface {
	Model
	Stream(context.Context, ModelRequest) (<-chan StreamEvent, error)
}

var (
	// ErrStreamingUnsupported marks models that only implement non-streaming generation.
	ErrStreamingUnsupported = errors.New("agent: streaming unsupported")
	// ErrStreamingToolCallsUnsupported marks streamed tool calls, which are not executed yet.
	ErrStreamingToolCallsUnsupported = errors.New("agent: streaming tool calls unsupported")
)

// StreamEventType identifies the kind of event produced by a streaming run.
type StreamEventType string

const (
	StreamEventDelta         StreamEventType = "delta"
	StreamEventThinkingDelta StreamEventType = "thinking_delta"
	StreamEventDone          StreamEventType = "done"
	StreamEventError         StreamEventType = "error"
	StreamEventToolCallStart StreamEventType = "tool_call_start"
	StreamEventToolCallDone  StreamEventType = "tool_call_done"
)

// StreamToolCall carries safe streamed tool-call boundary metadata. It never
// includes tool arguments or result content.
type StreamToolCall struct {
	// ID is the provider tool-call ID when available.
	ID string
	// Name is the registered tool name when available.
	Name string
	// Index is the provider stream index when available.
	Index int
}

// StreamFinishMetadata carries safe final stream completion metadata.
type StreamFinishMetadata struct {
	// Reason is the provider finish or stop reason when reported.
	Reason string
}

// StreamEvent carries one item from a streaming run. Delta contains incremental
// assistant text or provider thinking text, depending on Type. ToolCall contains
// safe metadata on tool-call boundary events. Message, Usage, and Finish are
// populated on done when available; Error is populated on error.
type StreamEvent struct {
	Type     StreamEventType
	AgentID  string
	Delta    string
	ToolCall StreamToolCall
	Message  Message
	// Usage reports final token counts when a streaming model/provider reports them.
	Usage TokenUsage
	// Finish reports safe provider completion metadata on final done events.
	Finish StreamFinishMetadata
	Error  error
}

// ModelRequest is the fully assembled prompt and capability set for one model call.
type ModelRequest struct {
	AgentID      string
	SystemPrompt string
	Messages     []Message
	Tools        []ToolDescriptor
	MCPServers   []MCPServerConfig
	ActiveSkills []skills.Skill
}

// TokenUsage reports model token counts when a provider or custom model makes
// them available.
type TokenUsage struct {
	// InputTokens is the number of tokens consumed by the model request.
	InputTokens int
	// OutputTokens is the number of tokens generated by the model response.
	OutputTokens int
	// TotalTokens is the provider-reported total token count.
	TotalTokens int
}

// ProviderDiagnostics carries safe provider metadata for model failures. It
// intentionally excludes request/response bodies, full URLs, credentials, and
// raw provider error text.
type ProviderDiagnostics struct {
	Provider     string
	HTTPStatus   int
	EndpointHost string
	RequestID    string
	// RetryAfter and RateLimit fields are bounded diagnostic header hints.
	RetryAfter         string
	RateLimitLimit     string
	RateLimitRemaining string
	RateLimitReset     string
}

// IsZero reports whether diagnostics contain no usable metadata.
func (d ProviderDiagnostics) IsZero() bool {
	return normalizeProviderDiagnostics(d) == ProviderDiagnostics{}
}

// ProviderDiagnosticsError is implemented by errors that expose sanitized
// provider metadata without requiring callers to inspect raw provider text.
type ProviderDiagnosticsError interface {
	SafeProviderDiagnostics() ProviderDiagnostics
}

// ModelErrorSubcategory identifies provider/model failure details suitable for
// log grouping and alert routing. It refines ErrorCategoryModel without
// replacing the high-level category.
type ModelErrorSubcategory string

const (
	ModelErrorSubcategoryTimeout        ModelErrorSubcategory = "timeout"
	ModelErrorSubcategoryRateLimited    ModelErrorSubcategory = "rate_limited"
	ModelErrorSubcategoryAuth           ModelErrorSubcategory = "auth"
	ModelErrorSubcategoryServerError    ModelErrorSubcategory = "server_error"
	ModelErrorSubcategoryBadRequest     ModelErrorSubcategory = "bad_request"
	ModelErrorSubcategoryDecodeError    ModelErrorSubcategory = "decode_error"
	ModelErrorSubcategoryTransportError ModelErrorSubcategory = "transport_error"
	ModelErrorSubcategoryUnknown        ModelErrorSubcategory = "unknown"
)

// ModelErrorSubcategoryError is implemented by errors that expose sanitized
// model/provider failure classification without requiring raw error parsing.
type ModelErrorSubcategoryError interface {
	SafeModelErrorSubcategory() ModelErrorSubcategory
}

// ProviderError is returned by built-in provider adapters when safe diagnostic
// metadata is available. Error intentionally omits the wrapped cause text; use
// Unwrap, errors.Is, or errors.As when programmatic access to the cause is
// needed.
type ProviderError struct {
	Message               string
	Diagnostics           ProviderDiagnostics
	ModelErrorSubcategory ModelErrorSubcategory
	Cause                 error
}

// NewProviderError wraps a provider failure with safe diagnostic metadata.
func NewProviderError(message string, diagnostics ProviderDiagnostics, cause error) *ProviderError {
	diagnostics = normalizeProviderDiagnostics(diagnostics)
	return &ProviderError{
		Message:               strings.TrimSpace(message),
		Diagnostics:           diagnostics,
		ModelErrorSubcategory: modelErrorSubcategoryFromHTTPStatus(diagnostics.HTTPStatus),
		Cause:                 cause,
	}
}

// NewProviderTransportError wraps a provider transport failure and classifies
// timeouts separately from other connection/request failures.
func NewProviderTransportError(message string, diagnostics ProviderDiagnostics, cause error) *ProviderError {
	subcategory := ModelErrorSubcategoryTransportError
	if isTimeoutError(cause) {
		subcategory = ModelErrorSubcategoryTimeout
	}
	return newProviderErrorWithModelErrorSubcategory(message, diagnostics, cause, subcategory)
}

// NewProviderDecodeError wraps a provider response decode failure.
func NewProviderDecodeError(message string, diagnostics ProviderDiagnostics, cause error) *ProviderError {
	return newProviderErrorWithModelErrorSubcategory(message, diagnostics, cause, ModelErrorSubcategoryDecodeError)
}

func newProviderErrorWithModelErrorSubcategory(message string, diagnostics ProviderDiagnostics, cause error, subcategory ModelErrorSubcategory) *ProviderError {
	err := NewProviderError(message, diagnostics, cause)
	err.ModelErrorSubcategory = normalizeModelErrorSubcategory(subcategory)
	if err.ModelErrorSubcategory == "" {
		err.ModelErrorSubcategory = ModelErrorSubcategoryUnknown
	}
	return err
}

func (e *ProviderError) Error() string {
	if e == nil {
		return ""
	}
	message := strings.TrimSpace(e.Message)
	if message == "" {
		message = "provider error"
	}
	return "agent: " + message
}

func (e *ProviderError) Unwrap() error {
	if e == nil {
		return nil
	}
	return e.Cause
}

func (e *ProviderError) SafeProviderDiagnostics() ProviderDiagnostics {
	if e == nil {
		return ProviderDiagnostics{}
	}
	return normalizeProviderDiagnostics(e.Diagnostics)
}

func (e *ProviderError) SafeModelErrorSubcategory() ModelErrorSubcategory {
	if e == nil {
		return ""
	}
	if subcategory := normalizeModelErrorSubcategory(e.ModelErrorSubcategory); subcategory != "" {
		return subcategory
	}
	if subcategory := modelErrorSubcategoryFromHTTPStatus(e.Diagnostics.HTTPStatus); subcategory != "" {
		return subcategory
	}
	return ModelErrorSubcategoryUnknown
}

// ProviderDiagnosticsFromError extracts safe provider diagnostics from an error
// chain when a built-in provider or custom model error exposes them.
func ProviderDiagnosticsFromError(err error) (ProviderDiagnostics, bool) {
	if err == nil {
		return ProviderDiagnostics{}, false
	}
	var agentErr *AgentError
	if errors.As(err, &agentErr) {
		if diagnostics := normalizeProviderDiagnostics(agentErr.ProviderDiagnostics); !diagnostics.IsZero() {
			return diagnostics, true
		}
		if agentErr.Cause != nil {
			if diagnostics, ok := ProviderDiagnosticsFromError(agentErr.Cause); ok {
				return diagnostics, true
			}
		}
	}
	var providerErr ProviderDiagnosticsError
	if errors.As(err, &providerErr) {
		if diagnostics := normalizeProviderDiagnostics(providerErr.SafeProviderDiagnostics()); !diagnostics.IsZero() {
			return diagnostics, true
		}
	}
	return ProviderDiagnostics{}, false
}

// ModelErrorSubcategoryFromError extracts a sanitized model/provider failure
// subcategory from an error chain when available.
func ModelErrorSubcategoryFromError(err error) (ModelErrorSubcategory, bool) {
	if err == nil {
		return "", false
	}
	var agentErr *AgentError
	if errors.As(err, &agentErr) {
		if subcategory := normalizeModelErrorSubcategory(agentErr.ModelErrorSubcategory); subcategory != "" {
			return subcategory, true
		}
		if agentErr.Cause != nil {
			if subcategory, ok := ModelErrorSubcategoryFromError(agentErr.Cause); ok {
				return subcategory, true
			}
		}
		if agentErr.Category == ErrorCategoryModel {
			return ModelErrorSubcategoryUnknown, true
		}
	}
	var subcategoryErr ModelErrorSubcategoryError
	if errors.As(err, &subcategoryErr) {
		if subcategory := normalizeModelErrorSubcategory(subcategoryErr.SafeModelErrorSubcategory()); subcategory != "" {
			return subcategory, true
		}
	}
	return "", false
}

func normalizeProviderDiagnostics(diagnostics ProviderDiagnostics) ProviderDiagnostics {
	diagnostics.Provider = strings.TrimSpace(diagnostics.Provider)
	diagnostics.EndpointHost = normalizeProviderEndpointHost(diagnostics.EndpointHost)
	diagnostics.RequestID = strings.TrimSpace(diagnostics.RequestID)
	diagnostics.RetryAfter = strings.TrimSpace(diagnostics.RetryAfter)
	diagnostics.RateLimitLimit = strings.TrimSpace(diagnostics.RateLimitLimit)
	diagnostics.RateLimitRemaining = strings.TrimSpace(diagnostics.RateLimitRemaining)
	diagnostics.RateLimitReset = strings.TrimSpace(diagnostics.RateLimitReset)
	if diagnostics.HTTPStatus < 100 || diagnostics.HTTPStatus > 999 {
		diagnostics.HTTPStatus = 0
	}
	return diagnostics
}

func normalizeProviderEndpointHost(endpoint string) string {
	endpoint = strings.TrimSpace(endpoint)
	if endpoint == "" {
		return ""
	}
	if parsed, err := url.Parse(endpoint); err == nil && parsed.Host != "" {
		return stripProviderEndpointUserInfo(parsed.Host)
	}
	host := endpoint
	for _, separator := range []string{"/", "?", "#"} {
		if index := strings.Index(host, separator); index >= 0 {
			host = host[:index]
		}
	}
	return stripProviderEndpointUserInfo(strings.TrimSpace(host))
}

func stripProviderEndpointUserInfo(host string) string {
	if index := strings.LastIndex(host, "@"); index >= 0 {
		return host[index+1:]
	}
	return host
}

func normalizeModelErrorSubcategory(subcategory ModelErrorSubcategory) ModelErrorSubcategory {
	switch ModelErrorSubcategory(strings.TrimSpace(string(subcategory))) {
	case "":
		return ""
	case ModelErrorSubcategoryTimeout:
		return ModelErrorSubcategoryTimeout
	case ModelErrorSubcategoryRateLimited:
		return ModelErrorSubcategoryRateLimited
	case ModelErrorSubcategoryAuth:
		return ModelErrorSubcategoryAuth
	case ModelErrorSubcategoryServerError:
		return ModelErrorSubcategoryServerError
	case ModelErrorSubcategoryBadRequest:
		return ModelErrorSubcategoryBadRequest
	case ModelErrorSubcategoryDecodeError:
		return ModelErrorSubcategoryDecodeError
	case ModelErrorSubcategoryTransportError:
		return ModelErrorSubcategoryTransportError
	case ModelErrorSubcategoryUnknown:
		return ModelErrorSubcategoryUnknown
	default:
		return ModelErrorSubcategoryUnknown
	}
}

func modelErrorSubcategoryFromHTTPStatus(status int) ModelErrorSubcategory {
	switch {
	case status == 0:
		return ModelErrorSubcategoryUnknown
	case status == 401 || status == 403:
		return ModelErrorSubcategoryAuth
	case status == 429:
		return ModelErrorSubcategoryRateLimited
	case status >= 400 && status <= 499:
		return ModelErrorSubcategoryBadRequest
	case status >= 500 && status <= 599:
		return ModelErrorSubcategoryServerError
	default:
		return ModelErrorSubcategoryUnknown
	}
}

func isTimeoutError(err error) bool {
	if err == nil {
		return false
	}
	if errors.Is(err, context.DeadlineExceeded) {
		return true
	}
	var timeout interface {
		Timeout() bool
	}
	return errors.As(err, &timeout) && timeout.Timeout()
}

// ModelResponse is the model output. It may return a final assistant message or tool calls.
type ModelResponse struct {
	Message   Message
	ToolCalls []ToolCall
	// Usage is optional. Its zero value means token usage was not reported.
	Usage TokenUsage
}

// Config defines the stable behavior of an Agent.
type Config struct {
	ID            string
	SystemPrompt  string
	Compact       CompactConfig
	MaxToolRounds int
}

// CompactConfig controls when and how the agent compacts conversation context.
type CompactConfig struct {
	MaxTokens int
	Threshold float64
	KeepLast  int
}

// TokenCounter estimates token usage for threshold checks.
type TokenCounter interface {
	Count(Message) int
}

// TokenCounterFunc adapts a function into a TokenCounter.
type TokenCounterFunc func(Message) int

func (f TokenCounterFunc) Count(message Message) int {
	return f(message)
}

// ApproxTokenCounter is a dependency-free token estimator suitable for threshold triggers.
type ApproxTokenCounter struct{}

func (ApproxTokenCounter) Count(message Message) int {
	content := strings.TrimSpace(message.Content)
	if content == "" {
		return 0
	}
	words := len(strings.Fields(content))
	chars := int(math.Ceil(float64(len(content)) / 4.0))
	if chars > words {
		return chars
	}
	return words
}

// Compactor replaces a long message history with a shorter one.
type Compactor interface {
	Compact(context.Context, []Message) ([]Message, error)
}

// SummaryCompactor creates a deterministic local summary when no model-backed compactor is provided.
type SummaryCompactor struct {
	KeepLast int
}

func (c SummaryCompactor) Compact(ctx context.Context, messages []Message) ([]Message, error) {
	keep := c.KeepLast
	if keep <= 0 {
		keep = 4
	}
	if len(messages) <= keep {
		return CloneMessages(messages), nil
	}
	summary := Message{
		Role:    RoleSystem,
		Content: fmt.Sprintf("Conversation compacted: %d earlier messages were summarized by the SDK.", len(messages)-keep),
	}
	result := []Message{summary}
	result = append(result, CloneMessages(messages[len(messages)-keep:])...)
	return result, nil
}

// ModelCompactor asks a model to summarize older context and keeps recent messages intact.
type ModelCompactor struct {
	Model        Model
	SystemPrompt string
	KeepLast     int
}

func (c ModelCompactor) Compact(ctx context.Context, messages []Message) ([]Message, error) {
	if c.Model == nil {
		return nil, errors.New("agent: compactor model is required")
	}
	keep := c.KeepLast
	if keep <= 0 {
		keep = 4
	}
	if len(messages) <= keep {
		return CloneMessages(messages), nil
	}

	older := CloneMessages(messages[:len(messages)-keep])
	recent := CloneMessages(messages[len(messages)-keep:])
	prompt := strings.TrimSpace(c.SystemPrompt)
	if prompt == "" {
		prompt = "Summarize the conversation context for a future agent turn. Preserve decisions, constraints, open tasks, and user preferences."
	}
	response, err := c.Model.Generate(ctx, ModelRequest{
		SystemPrompt: prompt,
		Messages:     older,
	})
	if err != nil {
		return nil, err
	}
	summary := strings.TrimSpace(response.Message.Content)
	if summary == "" {
		summary = "Earlier context was compacted, but the summarizer returned an empty summary."
	}
	result := []Message{{
		Role:    RoleSystem,
		Content: "Context summary:\n" + summary,
	}}
	result = append(result, recent...)
	return result, nil
}

// MCPTransport identifies how an MCP server is reached.
type MCPTransport string

const (
	MCPTransportStdio MCPTransport = "stdio"
	MCPTransportSSE   MCPTransport = "sse"
	MCPTransportHTTP  MCPTransport = "http"
)

// MCPServerConfig describes an MCP server available to an agent.
type MCPServerConfig struct {
	Name      string
	Command   string
	Args      []string
	Env       map[string]string
	URL       string
	Transport MCPTransport
}

// ToolDescriptor is the model-facing description of an available tool.
type ToolDescriptor struct {
	Name        string
	Description string
	Parameters  *schema.ToolParametersSchema
	Risk        ToolRisk
}

// ToolRisk labels the expected side-effect profile of a tool.
type ToolRisk string

const (
	ToolRiskUnspecified ToolRisk = ""
	ToolRiskRead        ToolRisk = "read"
	ToolRiskWrite       ToolRisk = "write"
	ToolRiskDestructive ToolRisk = "destructive"
)

// ToolScope binds a tool to an application-defined security boundary. Values
// can be sensitive, such as filesystem roots or tenant identifiers; lifecycle
// telemetry exposes only counts and hashes derived from scopes.
type ToolScope struct {
	Kind  string
	Value string
}

// ToolSafety declares local guardrails and approval context for a tool.
// Timeouts, concurrency limits, and result limits are enforced by the SDK.
// Scopes and BusinessReason are passed to approval policies, but observations
// receive only non-sensitive hashes and counts.
type ToolSafety struct {
	Risk           ToolRisk
	Timeout        time.Duration
	MaxConcurrency int
	MaxResultBytes int
	Scopes         []ToolScope
	BusinessReason string
}

// ToolSafetyProvider is an optional extension for tools that declare execution
// limits, scopes, or business approval context.
type ToolSafetyProvider interface {
	ToolSafety() ToolSafety
}

// ToolCall is a model request to execute a tool.
type ToolCall struct {
	ID        string
	Name      string
	Arguments map[string]any
}

// ToolResult is the output of a tool call.
type ToolResult struct {
	CallID   string
	Name     string
	Content  string
	Metadata map[string]any
}

// Tool is implemented by callable agent tools.
type Tool interface {
	Name() string
	Description() string
	Call(context.Context, ToolCall) (ToolResult, error)
}

// ToolParametersSchemaProvider is an optional extension for tools with JSON Schema parameters.
type ToolParametersSchemaProvider interface {
	ParametersSchema() *schema.ToolParametersSchema
}

// ToolRiskProvider is an optional extension for tools that declare side-effect risk.
type ToolRiskProvider interface {
	Risk() ToolRisk
}

// ToolFunc adapts a function into a Tool.
type ToolFunc struct {
	ToolName        string
	ToolDescription string
	Parameters      *schema.ToolParametersSchema
	ToolRisk        ToolRisk
	Safety          ToolSafety
	Fn              func(context.Context, ToolCall) (ToolResult, error)
}

func (t ToolFunc) Name() string {
	return t.ToolName
}

func (t ToolFunc) Description() string {
	return t.ToolDescription
}

func (t ToolFunc) ParametersSchema() *schema.ToolParametersSchema {
	return schema.Clone(t.Parameters)
}

func (t ToolFunc) Risk() ToolRisk {
	return t.ToolSafety().Risk
}

func (t ToolFunc) ToolSafety() ToolSafety {
	safety := CloneToolSafety(t.Safety)
	if safety.Risk == "" {
		safety.Risk = normalizeToolRisk(t.ToolRisk)
	}
	return safety
}

func (t ToolFunc) Call(ctx context.Context, call ToolCall) (ToolResult, error) {
	if t.Fn == nil {
		return ToolResult{}, errors.New("agent: tool function is nil")
	}
	return t.Fn(ctx, call)
}

// ApprovalRequest describes a tool call awaiting permission.
type ApprovalRequest struct {
	AgentID  string
	ToolName string
	Risk     ToolRisk
	// ToolSafety includes the registered tool's limits, scopes, and business
	// reason so approval policies can enforce application-specific boundaries.
	// ToolCall can still contain sensitive arguments; approval implementations
	// should avoid logging raw requests.
	ToolSafety ToolSafety
	ToolCall   ToolCall
}

// ApprovalDecision is the result of a permission check.
type ApprovalDecision struct {
	Approved bool
	Reason   string
}

// ApprovalPolicy decides whether a tool call may execute.
type ApprovalPolicy interface {
	ApproveTool(context.Context, ApprovalRequest) (ApprovalDecision, error)
}

// ApprovalFunc adapts a function into an ApprovalPolicy.
type ApprovalFunc func(context.Context, ApprovalRequest) (ApprovalDecision, error)

func (f ApprovalFunc) ApproveTool(ctx context.Context, request ApprovalRequest) (ApprovalDecision, error) {
	return f(ctx, request)
}

// AllowAllApproval approves every tool call.
type AllowAllApproval struct{}

func (AllowAllApproval) ApproveTool(context.Context, ApprovalRequest) (ApprovalDecision, error) {
	return ApprovalDecision{Approved: true, Reason: "allowed"}, nil
}

// TraceContext carries caller-provided trace correlation metadata. Values should
// be non-sensitive identifiers because the SDK surfaces them in lifecycle
// events, observations, and structured errors.
type TraceContext struct {
	TraceID    string
	SpanID     string
	TraceState string
}

type traceContextKey struct{}

// WithTraceContext attaches trace correlation metadata to ctx. The SDK only
// reads this typed value and does not inspect arbitrary context values.
func WithTraceContext(ctx context.Context, trace TraceContext) context.Context {
	trace = normalizeTraceContext(trace)
	if trace == (TraceContext{}) {
		return ctx
	}
	return context.WithValue(ctx, traceContextKey{}, trace)
}

// TraceContextFromContext returns trace correlation metadata previously attached
// with WithTraceContext.
func TraceContextFromContext(ctx context.Context) (TraceContext, bool) {
	if ctx == nil {
		return TraceContext{}, false
	}
	trace, ok := ctx.Value(traceContextKey{}).(TraceContext)
	if !ok {
		return TraceContext{}, false
	}
	trace = normalizeTraceContext(trace)
	return trace, trace != (TraceContext{})
}

func normalizeTraceContext(trace TraceContext) TraceContext {
	return TraceContext{
		TraceID:    strings.TrimSpace(trace.TraceID),
		SpanID:     strings.TrimSpace(trace.SpanID),
		TraceState: strings.TrimSpace(trace.TraceState),
	}
}

// ErrorCategory groups operational failures so callers can audit and branch
// without relying on provider-specific error text.
type ErrorCategory string

const (
	ErrorCategoryModel     ErrorCategory = "model"
	ErrorCategoryTool      ErrorCategory = "tool"
	ErrorCategoryApproval  ErrorCategory = "approval"
	ErrorCategorySchema    ErrorCategory = "schema"
	ErrorCategoryMCP       ErrorCategory = "mcp"
	ErrorCategoryCompact   ErrorCategory = "compact"
	ErrorCategorySubagent  ErrorCategory = "subagent"
	ErrorCategoryStreaming ErrorCategory = "streaming"
	ErrorCategorySession   ErrorCategory = "session"
	ErrorCategoryHook      ErrorCategory = "hook"
	ErrorCategoryConfig    ErrorCategory = "config"
)

// AgentError adds stable SDK context around an underlying error. Unwrap keeps
// existing sentinel checks such as errors.Is(err, ErrApprovalDenied) working.
type AgentError struct {
	Category   ErrorCategory
	Operation  string
	AgentID    string
	RunID      string
	TraceID    string
	SpanID     string
	TraceState string
	RequestID  string
	// ParentRequestID links nested failures to the request that caused them.
	ParentRequestID       string
	ToolName              string
	SubagentID            string
	Round                 int
	ProviderDiagnostics   ProviderDiagnostics
	ModelErrorSubcategory ModelErrorSubcategory
	Cause                 error
}

func (e *AgentError) Error() string {
	if e == nil {
		return ""
	}
	var parts []string
	if e.Category != "" {
		parts = append(parts, string(e.Category))
	}
	if e.Operation != "" {
		parts = append(parts, e.Operation)
	}
	if len(parts) == 0 {
		parts = append(parts, "operation")
	}
	message := "agent: " + strings.Join(parts, " ")
	if e.Cause == nil {
		return message
	}
	return fmt.Sprintf("%s: %v", message, e.Cause)
}

func (e *AgentError) Unwrap() error {
	if e == nil {
		return nil
	}
	return e.Cause
}

// EventType identifies a lifecycle hook event.
type EventType string

const (
	EventBeforeModel      EventType = "before_model"
	EventAfterModel       EventType = "after_model"
	EventBeforeApproval   EventType = "before_approval"
	EventAfterApproval    EventType = "after_approval"
	EventBeforeTool       EventType = "before_tool"
	EventAfterTool        EventType = "after_tool"
	EventBeforeCompact    EventType = "before_compact"
	EventAfterCompact     EventType = "after_compact"
	EventSkillActivated   EventType = "skill_activated"
	EventSubagentMessage  EventType = "subagent_message"
	EventStreamStart      EventType = "stream_start"
	EventStreamFirstDelta EventType = "stream_first_delta"
	EventStreamDone       EventType = "stream_done"
	EventStreamError      EventType = "stream_error"
)

// Event carries lifecycle data to hooks.
type Event struct {
	Type       EventType
	AgentID    string
	RunID      string
	SubagentID string
	ToolName   string
	ToolRisk   ToolRisk
	// ToolSchemaHash identifies the registered tool parameter schema and
	// descriptor metadata without exposing raw schema JSON or arguments.
	ToolSchemaHash string
	SkillName      string
	TraceID        string
	SpanID         string
	TraceState     string
	RequestID      string
	// ParentRequestID links nested lifecycle events to the request that caused them.
	ParentRequestID string
	Round           int
	Duration        time.Duration
	EstimatedTokens int
	// ToolTiming reports validation, approval, and execution timing for after-tool events.
	ToolTiming ToolLifecycleTiming
	// ToolSafety carries non-sensitive tool limit and scope audit metadata.
	ToolSafety ToolSafetyMetadata
	// TokenUsage reports provider or custom-model token counts when available.
	TokenUsage            TokenUsage
	StreamTelemetry       StreamTelemetry
	ProviderDiagnostics   ProviderDiagnostics
	ModelErrorSubcategory ModelErrorSubcategory
	Approved              bool
	ApprovalReason        string
	ErrorCategory         ErrorCategory
	Message               Message
	ToolCall              ToolCall
	ToolResult            ToolResult
	Error                 error
}

// Hook observes or rejects lifecycle events.
type Hook func(context.Context, Event) error

// Observer receives sanitized lifecycle metadata for production telemetry.
type Observer interface {
	Observe(context.Context, Observation)
}

// ObserverFunc adapts a function into an Observer.
type ObserverFunc func(context.Context, Observation)

func (f ObserverFunc) Observe(ctx context.Context, observation Observation) {
	if f != nil {
		f(ctx, observation)
	}
}

// NoopObserver drops every observation without output or dependencies.
type NoopObserver struct{}

func (NoopObserver) Observe(context.Context, Observation) {}

// StreamTelemetry contains sanitized counters and durations for a streaming
// model call. It intentionally omits streamed text content.
type StreamTelemetry struct {
	// TimeToFirstToken is the elapsed time from stream request start until the
	// first delta is received. It remains zero if no delta is received.
	TimeToFirstToken time.Duration
	// DeltaCount is the number of streamed delta events received.
	DeltaCount int
	// ByteCount is the total byte length of streamed delta text.
	ByteCount int
	// ThroughputBytesPerSecond is ByteCount divided by total stream duration.
	ThroughputBytesPerSecond float64
}

// ToolLifecycleTiming contains safe duration segments for a tool call. Duration
// on Event and Observation remains the total tool lifecycle duration.
type ToolLifecycleTiming struct {
	// Validation is time spent validating tool arguments before approval.
	Validation time.Duration
	// Approval is time spent waiting for the approval policy decision.
	Approval time.Duration
	// Execution is time spent in the tool implementation after approval.
	Execution time.Duration
}

func (t ToolLifecycleTiming) isZero() bool {
	return t.Validation == 0 && t.Approval == 0 && t.Execution == 0
}

// ToolResultMetadata contains safe metadata about a tool result. It never
// includes result content, metadata values, tool arguments, raw errors, or
// structured MCP content values.
type ToolResultMetadata struct {
	// ContentBytes is the byte length of ToolResult.Content.
	ContentBytes int
	// MetadataKeys lists ToolResult.Metadata key names in deterministic order.
	MetadataKeys []string
	// MCPIsError reports the MCP result error status when mcpIsError is present.
	MCPIsError *bool
}

func (m ToolResultMetadata) isZero() bool {
	return m.ContentBytes == 0 && len(m.MetadataKeys) == 0 && m.MCPIsError == nil
}

// ToolSafetyMetadata contains non-sensitive audit metadata derived from
// ToolSafety. It never includes raw scope values or business reasons.
type ToolSafetyMetadata struct {
	TimeoutConfigured  bool
	Timeout            time.Duration
	MaxConcurrency     int
	MaxResultBytes     int
	ScopeCount         int
	ScopeHash          string
	BusinessReasonHash string
}

func (m ToolSafetyMetadata) isZero() bool {
	return !m.TimeoutConfigured && m.Timeout == 0 && m.MaxConcurrency == 0 &&
		m.MaxResultBytes == 0 && m.ScopeCount == 0 && m.ScopeHash == "" &&
		m.BusinessReasonHash == ""
}

// Observation is a safe telemetry view of an Event. It intentionally omits
// message content, tool arguments, tool result content, tool result metadata
// values, raw errors, and MCP settings.
type Observation struct {
	Type       EventType
	AgentID    string
	RunID      string
	SubagentID string
	ToolName   string
	ToolRisk   ToolRisk
	// ToolSchemaHash identifies tool schema drift without exposing raw schema
	// JSON, tool arguments, or tool results.
	ToolSchemaHash string
	SkillName      string
	TraceID        string
	SpanID         string
	TraceState     string
	RequestID      string
	// ParentRequestID links nested telemetry records to the request that caused them.
	ParentRequestID string
	Round           int
	Duration        time.Duration
	EstimatedTokens int
	// ToolTiming reports safe validation, approval, and execution durations for
	// after-tool observations. Duration keeps its total lifecycle meaning.
	ToolTiming ToolLifecycleTiming
	// ToolSafety reports non-sensitive tool guardrail and scope metadata.
	ToolSafety ToolSafetyMetadata
	// TokenUsage reports sanitized real token counts when a model reports them.
	TokenUsage TokenUsage
	// StreamTelemetry reports sanitized counters and durations for streaming runs.
	StreamTelemetry StreamTelemetry
	// ProviderDiagnostics reports safe provider metadata for model failures.
	ProviderDiagnostics ProviderDiagnostics
	// ToolResultMetadata reports safe result size, metadata key names, and MCP
	// error status for after-tool observations.
	ToolResultMetadata ToolResultMetadata
	// ModelErrorSubcategory refines ErrorCategoryModel for safe alert grouping.
	ModelErrorSubcategory ModelErrorSubcategory
	Approved              bool
	ApprovalReason        string
	ErrorCategory         ErrorCategory
	Failed                bool
}

// ObservationFromEvent converts a lifecycle event into safe telemetry metadata.
func ObservationFromEvent(event Event) Observation {
	toolResultMetadata := toolResultMetadataFromEvent(event)
	return Observation{
		Type:                  event.Type,
		AgentID:               event.AgentID,
		RunID:                 event.RunID,
		SubagentID:            event.SubagentID,
		ToolName:              event.ToolName,
		ToolRisk:              event.ToolRisk,
		ToolSchemaHash:        event.ToolSchemaHash,
		SkillName:             event.SkillName,
		TraceID:               event.TraceID,
		SpanID:                event.SpanID,
		TraceState:            event.TraceState,
		RequestID:             event.RequestID,
		ParentRequestID:       event.ParentRequestID,
		Round:                 event.Round,
		Duration:              event.Duration,
		EstimatedTokens:       event.EstimatedTokens,
		ToolTiming:            event.ToolTiming,
		ToolSafety:            normalizeToolSafetyMetadata(event.ToolSafety),
		TokenUsage:            event.TokenUsage,
		StreamTelemetry:       event.StreamTelemetry,
		ProviderDiagnostics:   normalizeProviderDiagnostics(event.ProviderDiagnostics),
		ToolResultMetadata:    toolResultMetadata,
		ModelErrorSubcategory: normalizeModelErrorSubcategory(event.ModelErrorSubcategory),
		Approved:              event.Approved,
		ApprovalReason:        event.ApprovalReason,
		ErrorCategory:         event.ErrorCategory,
		Failed:                event.Error != nil || event.ErrorCategory != "",
	}
}

func toolResultMetadataFromEvent(event Event) ToolResultMetadata {
	if event.Type != EventAfterTool {
		return ToolResultMetadata{}
	}
	return toolResultMetadataFromToolResult(event.ToolResult)
}

func toolResultMetadataFromToolResult(result ToolResult) ToolResultMetadata {
	metadata := ToolResultMetadata{
		ContentBytes: len(result.Content),
		MetadataKeys: sortedToolResultMetadataKeys(result.Metadata),
		MCPIsError:   mcpIsErrorFromToolResultMetadata(result.Metadata),
	}
	if metadata.isZero() {
		return ToolResultMetadata{}
	}
	return metadata
}

func sortedToolResultMetadataKeys(metadata map[string]any) []string {
	if len(metadata) == 0 {
		return nil
	}
	keys := make([]string, 0, len(metadata))
	for key := range metadata {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}

func mcpIsErrorFromToolResultMetadata(metadata map[string]any) *bool {
	value, ok := metadata["mcpIsError"]
	if !ok {
		return nil
	}
	isError, ok := value.(bool)
	if !ok {
		return nil
	}
	return &isError
}

// CloneToolSafety returns a normalized deep copy of safety.
func CloneToolSafety(safety ToolSafety) ToolSafety {
	return normalizeToolSafety(safety)
}

// ToolSafetyMetadataFromSafety derives safe audit metadata from a tool safety
// policy without exposing raw scope values or business reasons.
func ToolSafetyMetadataFromSafety(safety ToolSafety) ToolSafetyMetadata {
	safety = normalizeToolSafety(safety)
	metadata := ToolSafetyMetadata{
		TimeoutConfigured: safety.Timeout > 0,
		Timeout:           safety.Timeout,
		MaxConcurrency:    safety.MaxConcurrency,
		MaxResultBytes:    safety.MaxResultBytes,
		ScopeCount:        len(safety.Scopes),
	}
	if len(safety.Scopes) > 0 {
		metadata.ScopeHash = hashToolScopes(safety.Scopes)
	}
	if safety.BusinessReason != "" {
		metadata.BusinessReasonHash = hashToolSafetyStrings("business_reason", safety.BusinessReason)
	}
	return normalizeToolSafetyMetadata(metadata)
}

func normalizeToolSafety(safety ToolSafety) ToolSafety {
	safety.Risk = normalizeToolRisk(safety.Risk)
	if safety.Timeout < 0 {
		safety.Timeout = 0
	}
	if safety.MaxConcurrency < 0 {
		safety.MaxConcurrency = 0
	}
	if safety.MaxResultBytes < 0 {
		safety.MaxResultBytes = 0
	}
	safety.BusinessReason = strings.TrimSpace(safety.BusinessReason)
	if len(safety.Scopes) > 0 {
		scopes := make([]ToolScope, 0, len(safety.Scopes))
		for _, scope := range safety.Scopes {
			scope.Kind = strings.TrimSpace(scope.Kind)
			scope.Value = strings.TrimSpace(scope.Value)
			if scope.Kind == "" && scope.Value == "" {
				continue
			}
			scopes = append(scopes, scope)
		}
		safety.Scopes = scopes
	}
	return safety
}

func normalizeToolRisk(risk ToolRisk) ToolRisk {
	return ToolRisk(strings.TrimSpace(string(risk)))
}

func normalizeToolSafetyMetadata(metadata ToolSafetyMetadata) ToolSafetyMetadata {
	if metadata.Timeout < 0 {
		metadata.Timeout = 0
	}
	if metadata.Timeout == 0 {
		metadata.TimeoutConfigured = false
	}
	if metadata.MaxConcurrency < 0 {
		metadata.MaxConcurrency = 0
	}
	if metadata.MaxResultBytes < 0 {
		metadata.MaxResultBytes = 0
	}
	if metadata.ScopeCount < 0 {
		metadata.ScopeCount = 0
	}
	metadata.ScopeHash = strings.TrimSpace(metadata.ScopeHash)
	metadata.BusinessReasonHash = strings.TrimSpace(metadata.BusinessReasonHash)
	if metadata.ScopeCount == 0 {
		metadata.ScopeHash = ""
	}
	return metadata
}

func hashToolScopes(scopes []ToolScope) string {
	scopes = append([]ToolScope(nil), scopes...)
	sort.Slice(scopes, func(i, j int) bool {
		if scopes[i].Kind == scopes[j].Kind {
			return scopes[i].Value < scopes[j].Value
		}
		return scopes[i].Kind < scopes[j].Kind
	})
	hasher := sha256.New()
	writeToolSafetyHashString(hasher, "cube-agent-sdk-tool-safety-v1")
	writeToolSafetyHashString(hasher, "scopes")
	writeToolSafetyHashUint64(hasher, uint64(len(scopes)))
	for _, scope := range scopes {
		writeToolSafetyHashString(hasher, scope.Kind)
		writeToolSafetyHashString(hasher, scope.Value)
	}
	return "sha256:" + hex.EncodeToString(hasher.Sum(nil))
}

func hashToolSafetyStrings(parts ...string) string {
	hasher := sha256.New()
	writeToolSafetyHashString(hasher, "cube-agent-sdk-tool-safety-v1")
	for _, part := range parts {
		writeToolSafetyHashString(hasher, part)
	}
	return "sha256:" + hex.EncodeToString(hasher.Sum(nil))
}

func writeToolSafetyHashString(hasher hash.Hash, value string) {
	writeToolSafetyHashUint64(hasher, uint64(len(value)))
	_, _ = hasher.Write([]byte(value))
}

func writeToolSafetyHashUint64(hasher hash.Hash, value uint64) {
	var buffer [8]byte
	binary.BigEndian.PutUint64(buffer[:], value)
	_, _ = hasher.Write(buffer[:])
}

// CloneMessages returns a deep copy of a message slice.
func CloneMessages(messages []Message) []Message {
	if len(messages) == 0 {
		return nil
	}
	cloned := make([]Message, len(messages))
	for i, message := range messages {
		cloned[i] = CloneMessage(message)
	}
	return cloned
}

// CloneMessage returns a deep copy of one message.
func CloneMessage(message Message) Message {
	message.ToolCalls = CloneToolCalls(message.ToolCalls)
	if len(message.Metadata) > 0 {
		message.Metadata = CloneAnyMap(message.Metadata)
	}
	return message
}

// CloneToolCalls returns a deep copy of tool calls.
func CloneToolCalls(calls []ToolCall) []ToolCall {
	if len(calls) == 0 {
		return nil
	}
	cloned := make([]ToolCall, len(calls))
	for i, call := range calls {
		cloned[i] = CloneToolCall(call)
	}
	return cloned
}

// CloneToolCall returns a deep copy of one tool call.
func CloneToolCall(call ToolCall) ToolCall {
	call.Arguments = CloneAnyMap(call.Arguments)
	return call
}

// CloneToolResult returns a deep copy of one tool result.
func CloneToolResult(result ToolResult) ToolResult {
	result.Metadata = CloneAnyMap(result.Metadata)
	return result
}

// CloneAnyMap deep-copies common container values used in metadata and arguments.
func CloneAnyMap(source map[string]any) map[string]any {
	if len(source) == 0 {
		return nil
	}
	cloned := make(map[string]any, len(source))
	for key, value := range source {
		cloned[key] = CloneAny(value)
	}
	return cloned
}

// CloneAny isolates container values commonly stored in metadata and tool arguments.
func CloneAny(value any) any {
	if value == nil {
		return nil
	}
	cloned := cloneAnyValue(reflect.ValueOf(value))
	if !cloned.IsValid() {
		return nil
	}
	return cloned.Interface()
}

func cloneAnyValue(value reflect.Value) reflect.Value {
	if !value.IsValid() {
		return value
	}
	switch value.Kind() {
	case reflect.Interface:
		if value.IsNil() {
			return reflect.Zero(value.Type())
		}
		return cloneAnyValue(value.Elem())
	case reflect.Pointer:
		if value.IsNil() {
			return reflect.Zero(value.Type())
		}
		cloned := reflect.New(value.Type().Elem())
		cloned.Elem().Set(cloneAssignableValue(value.Elem(), value.Type().Elem()))
		return cloned
	case reflect.Map:
		if value.IsNil() {
			return reflect.Zero(value.Type())
		}
		cloned := reflect.MakeMapWithSize(value.Type(), value.Len())
		iter := value.MapRange()
		for iter.Next() {
			cloned.SetMapIndex(iter.Key(), cloneAssignableValue(iter.Value(), value.Type().Elem()))
		}
		return cloned
	case reflect.Slice:
		if value.IsNil() {
			return reflect.Zero(value.Type())
		}
		cloned := reflect.MakeSlice(value.Type(), value.Len(), value.Len())
		for i := 0; i < value.Len(); i++ {
			cloned.Index(i).Set(cloneAssignableValue(value.Index(i), value.Type().Elem()))
		}
		return cloned
	case reflect.Array:
		cloned := reflect.New(value.Type()).Elem()
		for i := 0; i < value.Len(); i++ {
			cloned.Index(i).Set(cloneAssignableValue(value.Index(i), value.Type().Elem()))
		}
		return cloned
	default:
		return value
	}
}

func cloneAssignableValue(value reflect.Value, target reflect.Type) reflect.Value {
	cloned := cloneAnyValue(value)
	if !cloned.IsValid() {
		return reflect.Zero(target)
	}
	if cloned.Type().AssignableTo(target) {
		return cloned
	}
	if cloned.Type().ConvertibleTo(target) {
		return cloned.Convert(target)
	}
	if target.Kind() == reflect.Interface && cloned.Type().Implements(target) {
		return cloned
	}
	return value
}
